### ISSUE TITLE
Establish a Vagrant Template and Directory Standardizations

### ISSUE THREAD

**Issue by slsnow** [ZeTopHat/suse-vagrant-labs#2]

**Comment by ZeTopHat** [comment]
Initial files have been uploaded.

**Comment by slsnow** [comment]
# Structure thoughts

## custom.yaml and lab.yaml

I wondering if it's better to have separate {auth,basic,ha}.yaml files, or to include those values in the corresponding folder's custom.yaml. I kind of have mixed feeling here, and perhaps you can explain your thoughts 

## Many Vagrant Files or Many custom.yaml customizations

Is it better to have many different vagrant files, in their own directories (eg. auth/fulldeploy, auth/training)? Or would it make sense to have a single auth location, and parameters in the custom.yaml like `fulldeploy: "N"`. 

I guess it doesn't really have to be an either or thing, perhaps it can be both. I'll build mine out on monday following the structure you have so far to see if I have more of an opinion, haha. Just some thoughts. Happy weekend.

**Comment by ZeTopHat** [comment]
I think there are some variables that it makes sense to have lab specific (e.g. "suseconnect-d" and "labname"). Since those are set and shouldn't be changed. However, I think you are probably onto something with the "fulldeploy" variable in the "custom.yaml." I think that's a good idea.

**Comment by ZeTopHat** [comment]
What do you think of a "deployment:" variable that should have a value of "fulldeploy" or "training." This will further extend it to allow for more modulization possibilities in the future. (e.g. a cluster could have a "drbd" option to specifically deploy a drbd cluster.) We could also then just adjust the single Vagrantfile machines to do this:
`s.args = "#{LABNAME}iscsi custom_vars["deployment"]"`

**Comment by ZeTopHat** [comment]
I think we more or less have a directory standard at this point. While I'm sure we might find things to fix in the future. I think the initial purpose of this issue is good to be closed.
