### ISSUE TITLE
Figure out IP address standards

### ISSUE THREAD

**Issue by ZeTopHat** [ZeTopHat/suse-vagrant-labs#3]

**Comment by ZeTopHat** [comment]
Currently the IP addresses are static and set based on 192.168.0. I think it would be cool if we could figure out how to make that more dynamic. I don't know if that's something that would go in the custom.yaml or perhaps it would be a global.yaml or lab.yaml distinction. It's be worth looking into I think though. I think it'd be best to have a default, if possible, and then to allow for easy customization.

**Comment by slsnow** [comment]
Nice, this is looking sick!

In my vagrant files I had variables for:
- Bridged IP
- Subnet

I may even want multiple subnets for SUMA Proxy situations, so clients CANT communicate with SUMA directly. This could probably be a custom.yaml thing, but globally might be nice too, sometimes it might be nice to share subnets between different labs(e.g. have vagrant provision auth and suma labs at the same time for testing on the same subnet). 

Perhaps it would be best to:
- Have subnet variables that are global
  - There are default values
  - Can be configured based on the users environment
- The custom.yaml, lab yaml, and vagrant configure / provisioning can further define off of the global variables

I guess that last part would be the tricky part, I'll play around with an example on Monday and see what that looks like.

**Comment by ZeTopHat** [comment]
I would say that this has been resolved at this point. Per Sam's advice we did end up adding variables to the custom.yaml so that one could customize the subnet for their environment. I also ended up cleaning up static subnet values in the various projects (Sam handled SUMA) so that the primarysubnet variable is respected.
