### ISSUE TITLE
hana15 fulldeploy: sdb device persistence

### ISSUE THREAD

**Issue by slsnow** [ZeTopHat/suse-vagrant-labs#46]
I tested fencing a node. When it came back up, the sbd device had switched from `/dev/sdc` to `/dev/sdb`, and the value in /etc/sysconfig/sbd is configured for `SBD_DEVICE=/dev/sdc`, requiring some manual configuration to fix. 

It would be nice if during provisioning this was set by id to something more persistent.

**Comment by ZeTopHat** [comment]
Virtual machines don't really see change in disk names unless a device was removed or added. Were devices manually manipulated after the fact? I'm sure we can change things to use a persistent name, but it's never really been necessary.
